Name:           ros-jade-ecl-core-apps
Version:        0.61.4
Release:        0%{?dist}
Summary:        ROS ecl_core_apps package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/ecl_core_apps
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-ecl-command-line
Requires:       ros-jade-ecl-config
Requires:       ros-jade-ecl-containers
Requires:       ros-jade-ecl-converters
Requires:       ros-jade-ecl-devices
Requires:       ros-jade-ecl-errors
Requires:       ros-jade-ecl-exceptions
Requires:       ros-jade-ecl-formatters
Requires:       ros-jade-ecl-geometry
Requires:       ros-jade-ecl-ipc
Requires:       ros-jade-ecl-license
Requires:       ros-jade-ecl-linear-algebra
Requires:       ros-jade-ecl-sigslots
Requires:       ros-jade-ecl-streams
Requires:       ros-jade-ecl-threads
Requires:       ros-jade-ecl-time-lite
Requires:       ros-jade-ecl-type-traits
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-ecl-command-line
BuildRequires:  ros-jade-ecl-config
BuildRequires:  ros-jade-ecl-containers
BuildRequires:  ros-jade-ecl-converters
BuildRequires:  ros-jade-ecl-devices
BuildRequires:  ros-jade-ecl-errors
BuildRequires:  ros-jade-ecl-exceptions
BuildRequires:  ros-jade-ecl-formatters
BuildRequires:  ros-jade-ecl-geometry
BuildRequires:  ros-jade-ecl-ipc
BuildRequires:  ros-jade-ecl-license
BuildRequires:  ros-jade-ecl-linear-algebra
BuildRequires:  ros-jade-ecl-sigslots
BuildRequires:  ros-jade-ecl-streams
BuildRequires:  ros-jade-ecl-threads
BuildRequires:  ros-jade-ecl-time-lite
BuildRequires:  ros-jade-ecl-type-traits

%description
This includes a suite of programs demo'ing various aspects of the ecl_core. It
also includes various benchmarking and utility programs for use primarily with
embedded systems.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Oct 20 2015 Daniel Stonier <d.stonier@gmail.com> - 0.61.4-0
- Autogenerated by Bloom

