%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-ecl-core-apps
Version:        0.62.3
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ecl_core_apps package

License:        BSD
URL:            http://wiki.ros.org/ecl_core_apps
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-ecl-build
Requires:       ros-noetic-ecl-command-line
Requires:       ros-noetic-ecl-config
Requires:       ros-noetic-ecl-containers
Requires:       ros-noetic-ecl-converters
Requires:       ros-noetic-ecl-devices
Requires:       ros-noetic-ecl-errors
Requires:       ros-noetic-ecl-exceptions
Requires:       ros-noetic-ecl-formatters
Requires:       ros-noetic-ecl-geometry
Requires:       ros-noetic-ecl-ipc
Requires:       ros-noetic-ecl-license
Requires:       ros-noetic-ecl-linear-algebra
Requires:       ros-noetic-ecl-sigslots
Requires:       ros-noetic-ecl-streams
Requires:       ros-noetic-ecl-threads
Requires:       ros-noetic-ecl-time-lite
Requires:       ros-noetic-ecl-type-traits
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-ecl-build
BuildRequires:  ros-noetic-ecl-command-line
BuildRequires:  ros-noetic-ecl-config
BuildRequires:  ros-noetic-ecl-containers
BuildRequires:  ros-noetic-ecl-converters
BuildRequires:  ros-noetic-ecl-devices
BuildRequires:  ros-noetic-ecl-errors
BuildRequires:  ros-noetic-ecl-exceptions
BuildRequires:  ros-noetic-ecl-formatters
BuildRequires:  ros-noetic-ecl-geometry
BuildRequires:  ros-noetic-ecl-ipc
BuildRequires:  ros-noetic-ecl-license
BuildRequires:  ros-noetic-ecl-linear-algebra
BuildRequires:  ros-noetic-ecl-sigslots
BuildRequires:  ros-noetic-ecl-streams
BuildRequires:  ros-noetic-ecl-threads
BuildRequires:  ros-noetic-ecl-time-lite
BuildRequires:  ros-noetic-ecl-type-traits
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
This includes a suite of programs demo'ing various aspects of the ecl_core. It
also includes various benchmarking and utility programs for use primarily with
embedded systems.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Tue Jul 28 2020 Daniel Stonier <d.stonier@gmail.com> - 0.62.3-1
- Autogenerated by Bloom

