Name:           ros-melodic-ecl-core-apps
Version:        0.62.2
Release:        0%{?dist}
Summary:        ROS ecl_core_apps package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/ecl_core_apps
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-ecl-build
Requires:       ros-melodic-ecl-command-line
Requires:       ros-melodic-ecl-config
Requires:       ros-melodic-ecl-containers
Requires:       ros-melodic-ecl-converters
Requires:       ros-melodic-ecl-devices
Requires:       ros-melodic-ecl-errors
Requires:       ros-melodic-ecl-exceptions
Requires:       ros-melodic-ecl-formatters
Requires:       ros-melodic-ecl-geometry
Requires:       ros-melodic-ecl-ipc
Requires:       ros-melodic-ecl-license
Requires:       ros-melodic-ecl-linear-algebra
Requires:       ros-melodic-ecl-sigslots
Requires:       ros-melodic-ecl-streams
Requires:       ros-melodic-ecl-threads
Requires:       ros-melodic-ecl-time-lite
Requires:       ros-melodic-ecl-type-traits
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-ecl-build
BuildRequires:  ros-melodic-ecl-command-line
BuildRequires:  ros-melodic-ecl-config
BuildRequires:  ros-melodic-ecl-containers
BuildRequires:  ros-melodic-ecl-converters
BuildRequires:  ros-melodic-ecl-devices
BuildRequires:  ros-melodic-ecl-errors
BuildRequires:  ros-melodic-ecl-exceptions
BuildRequires:  ros-melodic-ecl-formatters
BuildRequires:  ros-melodic-ecl-geometry
BuildRequires:  ros-melodic-ecl-ipc
BuildRequires:  ros-melodic-ecl-license
BuildRequires:  ros-melodic-ecl-linear-algebra
BuildRequires:  ros-melodic-ecl-sigslots
BuildRequires:  ros-melodic-ecl-streams
BuildRequires:  ros-melodic-ecl-threads
BuildRequires:  ros-melodic-ecl-time-lite
BuildRequires:  ros-melodic-ecl-type-traits

%description
This includes a suite of programs demo'ing various aspects of the ecl_core. It
also includes various benchmarking and utility programs for use primarily with
embedded systems.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Sep 14 2018 Daniel Stonier <d.stonier@gmail.com> - 0.62.2-0
- Autogenerated by Bloom

* Sun May 13 2018 Daniel Stonier <d.stonier@gmail.com> - 0.62.1-0
- Autogenerated by Bloom

* Sat May 12 2018 Daniel Stonier <d.stonier@gmail.com> - 0.62.0-0
- Autogenerated by Bloom

